nohup: ignoring input
Executing:   0%|          | 0/15 [00:00<?, ?cell/s]Executing:   7%|6         | 1/15 [00:03<00:42,  3.04s/cell]Executing:  27%|##6       | 4/15 [01:56<02:28, 13.50s/cell]Executing:  40%|####      | 6/15 [01:57<01:25,  9.53s/cell]Executing:  53%|#####3    | 8/15 [01:57<00:46,  6.69s/cell]Executing:  67%|######6   | 10/15 [01:57<00:23,  4.70s/cell]Executing:  73%|#######3  | 11/15 [01:58<00:13,  3.43s/cell]Executing:  80%|########  | 12/15 [01:58<00:07,  2.47s/cell]Kernel died while waiting for execute reply.
Executing: 100%|##########| 15/15 [02:28<00:00,  4.76s/cell]Executing: 100%|##########| 15/15 [02:29<00:00,  9.95s/cell]
sys.argv: ['reports/subjectwise_model_evaluation/_dual_store_parametrize.py', 'data/Murdock1962.csv', 'subject > -1', 'Murdock1962']
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "C:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\asynchronous\channels.py", line 43, in get_msg
    ready = await self.socket.poll(timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gunnj\compmemlearn\reports\subjectwise_model_evaluation\_dual_store_parametrize.py", line 206, in <module>
    pm.execute_notebook(
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\execute.py", line 107, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\engines.py", line 359, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\engines.py", line 418, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "C:\ProgramData\Miniconda3\lib\site-packages\papermill\clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 845, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
